# NOTE: Activate 2 nodes in parallel on CircleCI
version: 2
jobs:
  "3.6":
    docker:
    - image: python:3.5-slim
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - pip-cache-{{ arch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
    - run:
        name: install dependencies
        command: |
          pip install -r requirements.txt -r requirements-dev.txt
    - save_cache:
        key: pip-cache-{{ arch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
        paths:
        - ~/.cache
    - run:
        name: test
        command: |
          ./entry.sh test
    - run:
        name: build
        command: |
          ./entry.sh build
    - run:
        name: install
        command: |
          pip install ~/repo
  "3.5":
    docker:
    - image: python:3.6-slim
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - pip-cache-{{ arch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements.txt" }}
    - run:
        name: install dependencies
        command: |
          pip install -r requirements.txt -r requirements-dev.txt
    - save_cache:
        key: pip-cache-{{ arch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
        paths:
        - ~/.cache
    - run:
        name: test
        command: |
          ./entry.sh test
    - run:
        name: build
        command: |
          ./entry.sh build
    - persist_to_workspace:
        root: /root
        paths:
        - repo
    - run:
        name: install
        command: |
          pip install ~/repo
    - run:
        name: codecov
        command: |
          apt-get update -y && apt-get install git -y
          ./entry.sh codecov

  "python-release":
    docker:
    - image: python:3.5-slim
    working_directory: ~/repo
    steps:
    - attach_workspace:
        at: /root
    - restore_cache:
        keys:
        - pip-cache-{{ arch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
    - run:
        name: install dependencies
        command: |
          pip install -r requirements-dev.txt
    - run:
        name: release
        command: |
          ./entry.sh publish

  "docker-release":
    docker:
    - image: docker
    working_directory: ~/repo
    steps:
    - attach_workspace:
        at: ~/repo
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: build and publish docker image
        command: |
          printf 'y' | docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
          docker build -t hypnosapos/jupyxplorer:latest -t hypnosapos/jupyxplorer:${CIRCLE_TAG} .
          docker push hypnosapos/jupyxplorer:${CIRCLE_TAG}
          docker push hypnosapos/jupyxplorer:latest

workflows:
  version: 2
  build:
    jobs:
    - "3.5"
    - "3.6"
    - "python-release":
        requires:
        - "3.5"
        - "3.6"
        filters:
          branches:
            only: master
    - "docker-release":
        requires:
        - "3.5"
        - "3.6"
        filters:
          branches:
            only: master
