# NOTE: Activate 2 nodes in parallel on CircleCI
version: 2
jobs:
  "3.6":
    docker:
    - image: python:3.5-slim
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - pycache-{{ arch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
    - run:
        name: install dependencies
        command: |
          pip install -r requirements.txt -r requirements-dev.txt
    - save_cache:
        key: pycache-{{ arch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
        paths:
        - /root/.cache
    - run:
        name: test
        command: |
          ~/repo/entry.sh test
    - run:
        name: build
        command: |
          ~/repo/entry.sh build
    - run:
        name: install
        command: |
          pip install ~/repo
  "3.5":
    docker:
    - image: python:3.6-slim
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - pycache-{{ arch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements.txt" }}
    - run:
        name: install dependencies
        command: |
          pip install -r requirements.txt -r requirements-dev.txt
    - save_cache:
        key: pycache-{{ arch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
        paths:
        - /root/.cache
    - run:
        name: test
        command: |
          ~/repo/entry.sh test
    - run:
        name: build
        command: |
          ~/repo/entry.sh build
    - run:
        name: codecov
        command: |
          ~/repo/entry.sh codecov
    - run:
        name: install
        command: |
          pip install ~/repo
  "python-release":
    docker:
    - image: python:3.5-slim
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - pycache-{{ arch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
    - run:
        name: install dependencies
        command: |
          pip install -r requirements-dev.txt
    - run:
        name: release
        command: |
          ~/repo/entry.sh publish
  "docker-release":
    docker:
    - image: docker:${DOCKER_VERSION}
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: build and publish docker image
        command: |
          docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
          docker build -t hypnosapos/jupyxplorer:latest -t hypnosapos/jupyxplorer:${CIRCLE_TAG} .
          docker push hypnosapos/jupyxplorer:${CIRCLE_TAG}
          docker push hypnosapos/jupyxplorer:latest

workflows:
  version: 2
  build:
    jobs:
    - "3.5"
    - "3.6"
    - "python-release":
        requires:
        - "3.5"
        - "3.6"
        filters:
          branches:
            only: master
    - "docker-release":
        requires:
        - "3.5"
        - "3.6"
        filters:
          tags:
            only: /^v.*/
